### ISSUE TITLE
代码实现

### ISSUE THREAD

**Issue by YANGDaping** [flysoaryun/LF-PGVIO#3]
您好，我看了您的代码，似乎并没有按照论文的逻辑去进行实现，而是直接用了ELSED，反而是通过降分辨率的方式来识别出这些“曲线”。请问我理解的是否正确？后期会不会上传按照论文逻辑实现的代码？

**Comment by flysoaryun** [comment]
Q:通过降分辨率的方式来识别出这些“曲线
A:并不是. cpp中降分辨率操作,只是因为图片太大了稍微降了分辨率.
我对ELSED的代码进行了较大改动, 可能有些cpp的名字没有特意重命名. 
代码基本上是严格按照论文写的,你可以全局搜索"by wz"查看我对ELSED算法的所有改动. 特别是(FullSegmentInfo.cpp)
