### ISSUE TITLE
代码复现

### ISSUE THREAD

**Issue by MerRuiDong** [flysoaryun/LF-PGVIO#4]
大佬你好，感谢你做的非常棒的工作！我结合你的ELSEDMatch和论文复现了RLBD描述子，运行的ID01数据集，描述子融合的时候也考虑了线段长度的权重，相机的参数也打开了，视频开头和结尾效果很好，但是在视频中间部分匹配的效果不太好，成功匹配的线段很少，想请教一下原因，我计算描述子调用的是你写的CalDescriptor，然后直接用cv::BinaryDescriptorMatcher做的match

**Comment by flysoaryun** [comment]
感谢对我们工作的认可, 视频中间部分匹配的效果不太好可能是由于该相机如果旋转速度较大的话,可能有一些模糊,造成匹配效果不佳,你也可以测试一下其他的序列.
